Repository Joy-Chang-2021/Twitter_project, pull requests merged in 2022-02, with the labels that each got.

#4 Readme 文件大綱更新
  README.md
Labels: PR attach

#23 Joy
  package-lock.json
  package.json
  src/components/ReplyCard.vue
  src/components/TweetCard.vue
  src/components/UserFollowCards.vue
  src/components/UserFollowTabs.vue
  src/main.js
  src/router/index.js
  src/scss/App.scss
  src/scss/_BasicElement.scss
  src/scss/_Icon.scss
  src/scss/_Main.scss
  src/scss/_ReplyCard.scss
  src/scss/_Tweet.scss
  src/scss/_TweetCard.scss
  src/scss/_UserFollowCards.scss
  src/scss/_UserFollowTabs.scss
  src/utils/mixins.js
  src/views/Main.vue
  src/views/Tweet.vue
  src/views/UserFollowers.vue
  src/views/UserFollowings.vue
Labels: documentation, Wiork in Process

#28 Joy
  package-lock.json
  package.json
  src/apis/authorization.js
  src/components/ReplyCard.vue
  src/components/ReplyCreate.vue
  src/components/TweetCard.vue
  src/components/TweetCreate.vue
  src/scss/App.scss
  src/scss/_BasicElement.scss
  src/scss/_Icon.scss
  src/scss/_Main.scss
  src/scss/_ReplyCreate.scss
  src/scss/_TweetCreate.scss
  src/store/index.js
  src/utils/helpers.js
  src/views/Main.vue
  src/views/SignIn.vue
  src/views/Tweet.vue
Labels: bug, Wiork in Process, 待測試
